name: notepad_forwangtao_writingboard
description: "为\"汪涛的记事本\"设计的书写板组件"
version: 0.0.1
homepage: https://github.com/TaoEngine

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^3.1.0
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/
